"use client";

import { useState, useRef } from "react";
import { 
  Sparkles, 
  Camera, 
  Video, 
  FileText, 
  LayoutGrid, 
  FileSearch,
  Users,
  ChevronRight,
  Loader2,
  Copy,
  Download,
  Upload,
  Zap,
  CheckCircle2
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

const AGENTS = [
  { id: "listing", title: "Listing Optimizer", icon: FileText, desc: "SEO-friendly titles, bullets, and A+ content.", color: "text-blue-500" },
  { id: "photoshoot", title: "Photoshoot Agent", icon: Camera, desc: "Prompt builder + style presets for high-end photography.", color: "text-purple-500" },
  { id: "video", title: "Video Ad Agent", icon: Video, desc: "Storyboard + text-to-video prompt generation.", color: "text-rose-500" },
  { id: "catalog", title: "Catalog Automation", icon: LayoutGrid, desc: "Template generation + marketplace rule validation.", color: "text-emerald-500" },
  { id: "ugc", title: "UGC Script Studio", icon: Users, desc: "10 hooks + detailed creator briefs & scripts.", color: "text-orange-500" },
  { id: "report", title: "Client Report Narrator", icon: FileSearch, desc: "Weekly performance analysis into readable narrative.", color: "text-indigo-500" },
];

export default function AgentsPage() {
  const [selectedAgent, setSelectedAgent] = useState<any>(null);
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState<any>(null);
  const [modelType, setModelType] = useState<string>("");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      toast({
        title: "File Ready",
        description: `Successfully prepared ${file.name} for AI analysis.`,
      });
    }
  };

  const handleRunAgent = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsRunning(true);
    
    // Simulate API delay
    await new Promise(r => setTimeout(r, 2000));
    
    // Mocked results based on agent type
    if (selectedAgent.id === 'listing') {
      setOutput({
        title: "Premium Handcrafted Silk Kurta - Midnight Blue",
        description: "Elevate your ethnic wardrobe with our Premium Handcrafted Silk Kurta. This midnight blue masterpiece is designed for the modern connoisseur, blending traditional artistry with a sophisticated contemporary fit. Perfect for weddings, festivals, and formal gatherings.",
        bullets: [
          "Authentic Mulberry Silk: Experience the luxury of 100% pure silk that breathes naturally.",
          "Exquisite Craftsmanship: Features intricate hand-stitched detailing along the placket.",
          "Modern Ethnic Cut: Tailored for a sharp, streamlined silhouette that offers comfort without bulk.",
          "Rich Color Depth: The deep midnight blue hue is achieved through eco-friendly dyeing processes.",
          "Versatile Styling: Pairs perfectly with ivory churidars or denim for a fusion look."
        ],
        type: 'listing'
      });
    } else {
      setOutput({
        title: "Optimized Premium Product",
        bullets: ["Premium Quality Material", "Ergonomic Design", "Durable Performance"],
        description: "A comprehensive description generated by our expert AI agent to maximize conversion.",
        prompt: "A high-fashion editorial shot of the product on a minimalist marble pedestal, soft natural light, 8k, photorealistic.",
        videoUrl: "https://picsum.photos/seed/video/600/400",
        type: 'creative'
      });
    }
    
    setIsRunning(false);
    toast({
      title: "Agent Execution Complete",
      description: "The AI has finished generating your content.",
    });
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied!",
      description: "Content copied to clipboard.",
    });
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-headline font-bold mb-1">AI Agents</h1>
        <p className="text-muted-foreground">Orchestrate specialized AI units to handle your marketplace tasks.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {AGENTS.map((agent) => (
          <Card key={agent.id} className="group hover:border-primary/50 transition-all rounded-2xl border-white/5 bg-card overflow-hidden cursor-pointer" onClick={() => setSelectedAgent(agent)}>
            <CardHeader>
              <div className={`w-12 h-12 rounded-xl bg-muted flex items-center justify-center mb-4 ${agent.color}`}>
                <agent.icon size={24} />
              </div>
              <CardTitle className="font-headline">{agent.title}</CardTitle>
              <CardDescription>{agent.desc}</CardDescription>
            </CardHeader>
            <CardFooter className="pt-0 justify-between">
              <span className="text-xs font-bold text-emerald-500 flex items-center">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mr-2" /> Ready
              </span>
              <Button variant="ghost" size="sm" className="opacity-0 group-hover:opacity-100 transition-opacity">
                Open Agent <ChevronRight size={14} className="ml-1" />
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      {/* Agent Modal */}
      <Dialog open={!!selectedAgent} onOpenChange={() => { setSelectedAgent(null); setOutput(null); setModelType(""); }}>
        <DialogContent className="max-w-3xl bg-card border-white/10 rounded-3xl overflow-hidden max-h-[90vh] flex flex-col p-0">
          {selectedAgent && (
            <>
              <DialogHeader className="p-8 pb-0">
                <div className="flex items-center gap-4 mb-2">
                  <div className={`w-10 h-10 rounded-lg bg-muted flex items-center justify-center ${selectedAgent.color}`}>
                    <selectedAgent.icon size={20} />
                  </div>
                  <div>
                    <DialogTitle className="text-2xl font-headline">{selectedAgent.title}</DialogTitle>
                    <DialogDescription>{selectedAgent.desc}</DialogDescription>
                  </div>
                </div>
              </DialogHeader>

              <div className="flex-1 overflow-y-auto p-8 pt-6">
                {!output ? (
                  <form onSubmit={handleRunAgent} className="space-y-8">
                    {/* Common Inputs */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Product Name</Label>
                        <Input placeholder="e.g. Silk Kurta" required />
                      </div>
                      <div className="space-y-2">
                        <Label>Category</Label>
                        <Select required>
                          <SelectTrigger>
                            <SelectValue placeholder="Select Category" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="fashion">Fashion</SelectItem>
                            <SelectItem value="apparels">Apparels</SelectItem>
                            <SelectItem value="other">Other</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      {selectedAgent.id === 'listing' && (
                        <div className="space-y-2">
                          <Label>Color</Label>
                          <Input placeholder="e.g. Midnight Blue" required />
                        </div>
                      )}
                    </div>

                    {/* Media Assets for Listing, Photoshoot, and Video */}
                    {(selectedAgent.id === 'listing' || selectedAgent.id === 'photoshoot' || selectedAgent.id === 'video') && (
                      <div className="space-y-6 bg-secondary/20 p-6 rounded-2xl border border-white/5">
                        <Label className="text-sm font-bold uppercase tracking-widest text-primary">Media Assets</Label>
                        <input 
                          type="file" 
                          className="hidden" 
                          ref={fileInputRef} 
                          onChange={handleFileChange} 
                          accept="image/*"
                          multiple
                        />
                        <div 
                          onClick={() => fileInputRef.current?.click()}
                          className="border-2 border-dashed border-white/10 rounded-xl p-8 flex flex-col items-center justify-center gap-4 hover:bg-secondary/30 transition-colors cursor-pointer group"
                        >
                           <Upload size={24} className="text-muted-foreground group-hover:text-primary transition-colors" />
                           <p className="text-sm font-medium">Upload product photos</p>
                           <Button type="button" variant="outline" size="sm">Select Files</Button>
                        </div>
                        
                        {/* Photoshoot/Video Specific Inputs */}
                        {(selectedAgent.id === 'photoshoot' || selectedAgent.id === 'video') && (
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div className="space-y-2">
                              <Label>Model Type</Label>
                              <Select onValueChange={(val) => setModelType(val)} required>
                                <SelectTrigger>
                                  <SelectValue placeholder="Select model style" />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="mens-ethnic">Mens Ethnic</SelectItem>
                                  <SelectItem value="female-ethnic">Female Ethnic</SelectItem>
                                  <SelectItem value="mens-casual">Mens Casual</SelectItem>
                                  <SelectItem value="female-casual">Female Casual</SelectItem>
                                  <SelectItem value="kids">Kids</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>
                            
                            {modelType === 'kids' && (
                              <div className="space-y-2 animate-in fade-in slide-in-from-top-2">
                                <Label>Age (Years)</Label>
                                <Input type="number" placeholder="Enter age" min="0" max="18" required />
                              </div>
                            )}

                            <div className="space-y-2">
                              <Label>Background Setting</Label>
                              <Select required>
                                <SelectTrigger>
                                  <SelectValue placeholder="Select environment" />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="pro-studio">Professional Studio</SelectItem>
                                  <SelectItem value="casual-outdoor">Casual Outdoor</SelectItem>
                                  <SelectItem value="heritage">Heritage Palace</SelectItem>
                                  <SelectItem value="modern-minimalist">Modern Minimalist</SelectItem>
                                  <SelectItem value="nature-garden">Nature/Garden</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>
                          </div>
                        )}
                      </div>
                    )}

                    {selectedAgent.id !== 'listing' && (
                      <div className="space-y-2">
                        <Label>Key Features or Brand Guidelines</Label>
                        <Textarea placeholder="List main selling points, brand tone, or specific requirements..." className="min-h-[100px]" />
                      </div>
                    )}

                    <Button type="submit" className="w-full h-14 rounded-xl text-lg font-bold shadow-xl shadow-primary/20" disabled={isRunning}>
                      {isRunning ? (
                        <><Loader2 className="mr-2 h-5 w-5 animate-spin" /> Agent is processing...</>
                      ) : (
                        <><Zap className="mr-2 h-5 w-5" /> Execute Agent</>
                      )}
                    </Button>
                  </form>
                ) : (
                  <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4">
                    <div className="p-8 rounded-2xl bg-secondary/30 border border-white/5 space-y-6">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                           <Sparkles className="text-primary" size={20} />
                           <h4 className="font-bold font-headline text-xl text-primary">Intelligence Output</h4>
                        </div>
                        <div className="flex gap-2">
                          <Button variant="ghost" size="icon" onClick={() => copyToClipboard(JSON.stringify(output))}><Copy size={16} /></Button>
                          <Button variant="ghost" size="icon"><Download size={16} /></Button>
                        </div>
                      </div>
                      
                      <div className="grid grid-cols-1 gap-6 text-sm">
                        {output.title && (
                          <div className="space-y-2">
                            <Label className="text-muted-foreground">Generated Title</Label>
                            <div className="p-4 bg-background rounded-xl border font-bold text-foreground">{output.title}</div>
                          </div>
                        )}
                        
                        {output.bullets && (
                          <div className="space-y-2">
                            <Label className="text-muted-foreground">Key Features (Bullet Points)</Label>
                            <div className="p-4 bg-background rounded-xl border space-y-2">
                              {output.bullets.map((bullet: string, i: number) => (
                                <div key={i} className="flex gap-2 items-start">
                                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                  <span className="text-foreground">{bullet}</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                        
                        {output.type === 'creative' && (
                          <div className="space-y-2">
                            <Label className="text-muted-foreground">Generated Prompt / Preview</Label>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="p-4 bg-background rounded-xl border italic text-muted-foreground text-xs leading-relaxed">
                                "{output.prompt}"
                              </div>
                              <div className="aspect-video bg-muted rounded-xl flex items-center justify-center overflow-hidden border">
                                <img src={output.videoUrl} alt="Preview" className="w-full h-full object-cover" />
                              </div>
                            </div>
                          </div>
                        )}

                        {output.description && (
                          <div className="space-y-2">
                            <Label className="text-muted-foreground">Detailed Description</Label>
                            <div className="p-4 bg-background rounded-xl border text-foreground leading-relaxed whitespace-pre-wrap">
                              {output.description}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                    <Button variant="outline" className="w-full h-12 rounded-xl" onClick={() => setOutput(null)}>Start New Task</Button>
                  </div>
                )}
              </div>
              
              <div className="p-3 bg-muted/30 border-t flex items-center justify-center gap-2">
                <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold">Authenticated AI Instance active</span>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
