"use client";

import { useState, useRef } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { 
  ArrowRight, 
  Sparkles, 
  Camera, 
  Video, 
  FileText, 
  LayoutGrid, 
  TrendingUp,
  BrainCircuit,
  Star,
  Upload,
  CheckCircle2,
  MapPin,
  Mail,
  Phone,
  Menu,
  X,
  ShoppingBag,
  ShoppingCart,
  Tag,
  Package,
  Truck,
  CreditCard
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
  DialogFooter
} from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";

export default function LandingPage() {
  const [demoOpen, setDemoOpen] = useState(false);
  const [serviceOpen, setServiceOpen] = useState<string | null>(null);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      toast({
        title: "File Selected",
        description: `Preparing to process: ${file.name}`,
      });
    }
  };

  const services = [
    { 
      id: "photoshoot",
      icon: Camera, 
      title: "AI Photoshoot", 
      desc: "Hyper-realistic product images in any environment without a physical set.",
      details: "Our AI Photoshoot agent generates high-fidelity backgrounds and context-aware lighting for your products. Simply upload a raw image and describe the setting.",
      hasUpload: true
    },
    { 
      id: "flyer",
      icon: Star, 
      title: "AI Flyer", 
      desc: "High-impact promotional graphics generated by AI for social media and marketplace banners.",
      details: "Our AI Flyer agent creates professional-grade marketing assets tailored for your brand's aesthetic. Perfect for sales, new arrivals, and social media campaigns.",
      hasUpload: true
    },
    { 
      id: "video",
      icon: Video, 
      title: "AI Video Ad Creation", 
      desc: "Convert product images into scroll-stopping 15s video advertisements.",
      details: "Turn static product shots into dynamic cinematic videos. Ideal for Instagram Reels, YouTube Shorts, and Amazon Video Ads.",
      hasUpload: true
    },
    { 
      id: "listing",
      icon: FileText, 
      title: "AI Listing Optimization", 
      desc: "Keyword-rich titles and descriptions optimized for platform algorithms.",
      details: "Our SEO agent analyzes competitor data and marketplace search trends to write high-converting copy for Amazon, Flipkart, and Myntra."
    },
    { 
      id: "catalog",
      icon: LayoutGrid, 
      title: "AI Catalog Automation", 
      desc: "Bulk upload preparation and validation for all major marketplaces.",
      details: "Automate the tedious task of marketplace sheet preparation. Validates attributes against marketplace-specific rules instantly."
    },
    { 
      id: "growth",
      icon: TrendingUp, 
      title: "Growth Intelligence", 
      desc: "Predictive analytics to outsmart competitors and scale ROAS.",
      details: "Data-driven recommendations for pricing, inventory, and advertising strategy based on real-time market shifts."
    },
  ];

  return (
    <div className="flex flex-col min-h-screen">
      {/* Navbar */}
      <header className="fixed top-0 w-full z-50 border-b border-white/5 bg-background/80 backdrop-blur-xl">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <BrainCircuit className="text-primary w-8 h-8" />
            <span className="font-headline font-bold text-xl tracking-tight">MarketMind AI</span>
          </Link>
          
          <nav className="hidden md:flex items-center gap-8 text-sm font-medium text-muted-foreground">
            <a href="#services" className="hover:text-primary transition-colors">Services</a>
            <a href="#how-it-works" className="hover:text-primary transition-colors">How it works</a>
            <Link href="/pricing" className="hover:text-primary transition-colors">Pricing</Link>
            <a href="#about" className="hover:text-primary transition-colors">About</a>
          </nav>

          <div className="flex items-center gap-4">
            <Link href="/login" className="hidden sm:inline-flex">
              <Button variant="ghost">Login</Button>
            </Link>
            <Link href="/signup" className="hidden sm:inline-flex">
              <Button className="rounded-full px-6">Start Free Trial</Button>
            </Link>
            
            {/* Mobile Menu Toggle */}
            <Sheet open={isMobileMenuOpen} onOpenChange={setIsMobileMenuOpen}>
              <SheetTrigger asChild>
                <Button variant="ghost" size="icon" className="md:hidden">
                  <Menu size={24} />
                </Button>
              </SheetTrigger>
              <SheetContent side="right" className="bg-background border-white/5 pt-12">
                <div className="flex flex-col gap-6 text-lg font-bold">
                  <a href="#services" onClick={() => setIsMobileMenuOpen(false)}>Services</a>
                  <a href="#how-it-works" onClick={() => setIsMobileMenuOpen(false)}>How it works</a>
                  <Link href="/pricing" onClick={() => setIsMobileMenuOpen(false)}>Pricing</Link>
                  <a href="#about" onClick={() => setIsMobileMenuOpen(false)}>About</a>
                  <hr className="border-white/5" />
                  <div className="flex flex-col gap-3">
                    <Link href="/login" onClick={() => setIsMobileMenuOpen(false)}>
                      <Button variant="outline" className="w-full h-12 rounded-xl">Login</Button>
                    </Link>
                    <Link href="/signup" onClick={() => setIsMobileMenuOpen(false)}>
                      <Button className="w-full h-12 rounded-xl">Get Started Now</Button>
                    </Link>
                  </div>
                </div>
              </SheetContent>
            </Sheet>
          </div>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative pt-32 pb-20 md:pt-48 md:pb-32 overflow-hidden hero-gradient">
          {/* Sprinkled Graphics */}
          <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
            <div className="absolute top-[15%] left-[10%] opacity-20 text-primary animate-float">
              <ShoppingBag size={48} />
            </div>
            <div className="absolute top-[25%] right-[15%] opacity-10 text-accent animate-float-delayed">
              <ShoppingCart size={64} />
            </div>
            <div className="absolute bottom-[20%] left-[20%] opacity-15 text-primary animate-float-delayed">
              <Tag size={32} />
            </div>
            <div className="absolute top-[40%] right-[5%] opacity-10 text-amber-500 animate-float">
              <Package size={56} />
            </div>
            <div className="absolute bottom-[30%] right-[25%] opacity-20 text-primary animate-float">
              <Truck size={40} />
            </div>
            <div className="absolute top-[10%] right-[30%] opacity-5 text-accent animate-float-delayed">
              <CreditCard size={38} />
            </div>
          </div>

          <div className="container mx-auto px-4 text-center relative z-10">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 text-[10px] font-bold mb-6 animate-fade-in">
              <Sparkles size={12} />
              <span>Next-Gen E-commerce Intelligence</span>
            </div>
            
            <div className="relative inline-block">
              <h1 className="font-headline text-4xl md:text-7xl font-bold mb-6 tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-amber-200 via-yellow-500 to-amber-600 leading-[1.1]">
                Grow Faster on Amazon, <br className="hidden md:block" /> Flipkart & Myntra with AI
              </h1>
              {/* Subtle accent graphics around text */}
              <div className="hidden lg:block absolute -top-8 -left-8 text-amber-500/20 animate-pulse">
                <Star size={32} fill="currentColor" />
              </div>
              <div className="hidden lg:block absolute -bottom-4 -right-8 text-primary/20 animate-bounce">
                <Sparkles size={32} />
              </div>
            </div>

            <p className="text-muted-foreground text-base md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed px-4">
              Automate your marketplace operations with expert-trained AI agents for photoshoots, listings, video ads, and growth intelligence.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 px-4">
              <Link href="/signup" className="w-full sm:w-auto">
                <Button size="lg" className="rounded-full px-8 text-lg h-14 w-full shadow-2xl shadow-primary/40">
                  Get Started Now <ArrowRight size={20} className="ml-2" />
                </Button>
              </Link>
              <Button 
                size="lg" 
                variant="outline" 
                className="rounded-full px-8 text-lg h-14 w-full sm:w-auto"
                onClick={() => setDemoOpen(true)}
              >
                Book a Demo
              </Button>
            </div>
          </div>

          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[120%] h-[120%] opacity-30 pointer-events-none">
            <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/30 rounded-full blur-[128px]" />
            <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-accent/30 rounded-full blur-[128px]" />
          </div>
        </section>

        {/* Services Showcase */}
        <section id="services" className="py-24 bg-secondary/20">
          <div className="container mx-auto px-4">
            <div className="text-center mb-16">
              <h2 className="font-headline text-3xl md:text-4xl font-bold mb-4">Our AI Agency Capabilities</h2>
              <p className="text-muted-foreground max-w-xl mx-auto">Five core agents designed to eliminate your operational bottlenecks.</p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
              {services.map((service) => (
                <div key={service.id} onClick={() => setServiceOpen(service.id)} className="cursor-pointer">
                  <ServiceCard 
                    icon={service.icon} 
                    title={service.title} 
                    desc={service.desc} 
                  />
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How it Works */}
        <section id="how-it-works" className="py-24 px-4">
          <div className="container mx-auto">
             <div className="text-center mb-16">
              <h2 className="font-headline text-3xl md:text-4xl font-bold mb-4">How It Works</h2>
              <p className="text-muted-foreground max-w-xl mx-auto">Three simple steps to supercharge your marketplace growth.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
              <div className="text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary mx-auto text-2xl font-bold">1</div>
                <h3 className="text-xl font-bold font-headline">Connect Store</h3>
                <p className="text-muted-foreground">Link your Amazon, Flipkart or Myntra seller central accounts in seconds.</p>
              </div>
              <div className="text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary mx-auto text-2xl font-bold">2</div>
                <h3 className="text-xl font-bold font-headline">AI Audit</h3>
                <p className="text-muted-foreground">Our agents scan your listings, catalog, and ads for optimization opportunities.</p>
              </div>
              <div className="text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary mx-auto text-2xl font-bold">3</div>
                <h3 className="text-xl font-bold font-headline">Scale ROAS</h3>
                <p className="text-muted-foreground">Apply AI recommendations instantly to boost conversion and reduce ad spend.</p>
              </div>
            </div>
          </div>
        </section>

        {/* About & Contact Section */}
        <section id="about" className="py-24 bg-secondary/10 px-4">
          <div className="container mx-auto">
            <div className="max-w-4xl mx-auto">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                <div>
                  <h2 className="font-headline text-3xl md:text-4xl font-bold mb-6">About MarketMind AI</h2>
                  <p className="text-muted-foreground mb-6 leading-relaxed text-lg">
                    We are a next-generation e-commerce growth agency powered by proprietary AI intelligence. Our mission is to democratize high-end creative production and strategic growth for brands selling on India's premier marketplaces.
                  </p>
                  <p className="text-muted-foreground leading-relaxed text-lg">
                    By combining expert marketplace knowledge with cutting-edge GenAI, we deliver results that were previously only accessible to enterprise brands with massive budgets.
                  </p>
                </div>
                <div className="space-y-8 bg-card border p-6 md:p-8 rounded-3xl shadow-xl">
                  <h3 className="text-2xl font-bold font-headline mb-4">Get In Touch</h3>
                  <div className="space-y-6">
                    <div className="flex items-start gap-4">
                      <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
                        <MapPin size={20} />
                      </div>
                      <div>
                        <p className="font-bold mb-1">Office Address</p>
                        <p className="text-muted-foreground text-sm">Udyog Vihar Phase-1 Gurgaon 122016 Haryana India</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
                        <Mail size={20} />
                      </div>
                      <div>
                        <p className="font-bold mb-1">Email Support</p>
                        <p className="text-muted-foreground text-sm">info@marketmindai.com</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
                        <Phone size={20} />
                      </div>
                      <div>
                        <p className="font-bold mb-1">Mobile</p>
                        <p className="text-muted-foreground text-sm">+91 88821 30155</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Demo Modal */}
      <Dialog open={demoOpen} onOpenChange={setDemoOpen}>
        <DialogContent className="sm:max-w-md rounded-3xl p-6">
          <DialogHeader>
            <DialogTitle className="text-2xl font-headline font-bold">Book a Strategy Session</DialogTitle>
            <DialogDescription>
              Schedule a 15-minute demo with our growth experts.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name">Full Name</Label>
              <Input id="name" placeholder="John Doe" className="rounded-xl" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Work Email</Label>
              <Input id="email" type="email" placeholder="john@company.com" className="rounded-xl" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="company">Company Name</Label>
              <Input id="company" placeholder="DTC Brand Ltd" className="rounded-xl" />
            </div>
          </div>
          <DialogFooter className="flex flex-col sm:flex-row gap-2">
            <Button onClick={() => setDemoOpen(false)} variant="outline" className="flex-1 rounded-xl h-12 order-2 sm:order-1">Cancel</Button>
            <Button onClick={() => setDemoOpen(false)} className="flex-1 rounded-xl h-12 order-1 sm:order-2">Schedule Demo</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Service Detail Modal */}
      <Dialog open={!!serviceOpen} onOpenChange={() => setServiceOpen(null)}>
        <DialogContent className="max-w-2xl rounded-3xl overflow-hidden p-0 max-h-[90vh] flex flex-col">
          {serviceOpen && (
            <>
              <div className="p-6 md:p-8 bg-card border-b shrink-0">
                <div className="flex items-center gap-4 mb-4">
                   <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                      {(() => {
                        const s = services.find(s => s.id === serviceOpen);
                        const Icon = s?.icon || Camera;
                        return <Icon size={24} />;
                      })()}
                   </div>
                   <DialogTitle className="text-2xl md:text-3xl font-headline font-bold">
                    {services.find(s => s.id === serviceOpen)?.title}
                   </DialogTitle>
                </div>
                <DialogDescription className="text-base md:text-lg leading-relaxed text-muted-foreground">
                  {services.find(s => s.id === serviceOpen)?.details}
                </DialogDescription>
              </div>
              
              <div className="p-6 md:p-8 space-y-6 overflow-y-auto">
                {services.find(s => s.id === serviceOpen)?.hasUpload && (
                  <div className="space-y-4">
                    <Label className="text-sm font-bold uppercase tracking-wider text-muted-foreground">Demo Preview</Label>
                    <input 
                      type="file" 
                      className="hidden" 
                      ref={fileInputRef} 
                      onChange={handleFileChange}
                      accept="image/*"
                    />
                    <div 
                      onClick={() => {
                        if (fileInputRef.current) fileInputRef.current.click();
                      }}
                      className="border-2 border-dashed border-white/10 rounded-2xl p-8 md:p-12 flex flex-col items-center justify-center gap-4 bg-secondary/20 hover:bg-secondary/30 transition-colors cursor-pointer group"
                    >
                      <div className="w-12 h-12 md:w-16 md:h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                        <Upload size={28} />
                      </div>
                      <div className="text-center">
                        <p className="font-bold text-lg">Upload Product Image</p>
                        <p className="text-xs text-muted-foreground">Drag and drop or click to browse</p>
                      </div>
                      <Button variant="outline" className="rounded-full h-10">Select File</Button>
                    </div>
                  </div>
                )}

                <div className="space-y-4">
                  <h4 className="font-bold font-headline flex items-center gap-2">
                    <CheckCircle2 size={18} className="text-primary" /> Key Benefits
                  </h4>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <li className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1 h-1 rounded-full bg-primary" /> 24/7 Automation
                    </li>
                    <li className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1 h-1 rounded-full bg-primary" /> Marketplace Compliant
                    </li>
                    <li className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1 h-1 rounded-full bg-primary" /> Multi-platform support
                    </li>
                    <li className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1 h-1 rounded-full bg-primary" /> High ROAS Efficiency
                    </li>
                  </ul>
                </div>

                <div className="pt-4 flex flex-col sm:flex-row gap-4">
                  <Link href="/signup" className="flex-1">
                    <Button className="w-full h-12 rounded-xl text-lg font-bold">Get Started Now</Button>
                  </Link>
                  <Button variant="outline" className="h-12 rounded-xl px-8" onClick={() => setServiceOpen(null)}>Close</Button>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Footer */}
      <footer className="border-t py-16 bg-background px-4">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-12 mb-12">
            <div className="col-span-1">
              <Link href="/" className="flex items-center gap-2 mb-6 hover:opacity-80 transition-opacity">
                <BrainCircuit className="text-primary w-6 h-6" />
                <span className="font-headline font-bold text-lg">MarketMind AI</span>
              </Link>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Leading e-commerce growth agency scaling brands on India's biggest marketplaces with AI.
              </p>
            </div>
            <div>
              <h4 className="font-bold mb-4">Services</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>AI Photoshoots</li>
                <li>Listing Optimization</li>
                <li>Video Ad Creation</li>
                <li>Catalog Automation</li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-4">Contact</h4>
              <ul className="space-y-4 text-sm text-muted-foreground">
                <li className="flex gap-2">
                  <MapPin size={16} className="text-primary shrink-0" />
                  <span>Udyog Vihar Phase-1 Gurgaon 122016</span>
                </li>
                <li className="flex gap-2 items-center">
                  <Mail size={16} className="text-primary shrink-0" />
                  <span>info@marketmindai.com</span>
                </li>
                <li className="flex gap-2 items-center">
                  <Phone size={16} className="text-primary shrink-0" />
                  <span>+91 88821 30155</span>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-primary transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Terms of Service</a></li>
              </ul>
            </div>
          </div>
          <div className="pt-8 border-t flex flex-col md:flex-row justify-between items-center gap-6">
            <p className="text-muted-foreground text-xs text-center md:text-left">© 2024 MarketMind AI. All rights reserved.</p>
            <div className="flex items-center gap-4">
              <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center cursor-pointer hover:bg-primary transition-colors">
                <span className="text-[10px] font-bold">LI</span>
              </div>
              <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center cursor-pointer hover:bg-primary transition-colors">
                <span className="text-[10px] font-bold">X</span>
              </div>
              <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center cursor-pointer hover:bg-primary transition-colors">
                <span className="text-[10px] font-bold">IG</span>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

function ServiceCard({ icon: Icon, title, desc }: { icon: any, title: string, desc: string }) {
  return (
    <Card className="group hover:border-primary/50 transition-all duration-300 border-white/5 bg-white/5 backdrop-blur-sm rounded-2xl overflow-hidden h-full">
      <CardContent className="p-6 md:p-8">
        <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary mb-6 group-hover:scale-110 transition-transform">
          <Icon size={24} />
        </div>
        <h3 className="font-headline text-lg md:text-xl font-bold mb-3">{title}</h3>
        <p className="text-muted-foreground text-sm md:text-base leading-relaxed">{desc}</p>
      </CardContent>
    </Card>
  );
}
